### ISSUE TITLE
(0x800B010A)

### ISSUE THREAD

**Issue by Mr-Dalgleish** [DmitryBorodiy/PowerWidgets#3]
Hi,

While installing the UWP file from the OneDrive link, I ran into an error. 

_"This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)"_

I have however installed the certificate in the ZIP file, but I still run into this issue.
![Screenshot (1)](https://user-images.githubusercontent.com/71429090/127770642-42d0adcf-17e1-4767-8d3e-1902c290ac0c.png)

**Comment by DmitryBorodiy** [comment]
Hello, please sorry for this issue you can download the stable version here:
https://dmitryborodiy.github.io/PowerDesktop/www/download.html
