### ISSUE TITLE
this is not an issue this is a suggestion

### ISSUE THREAD

**Issue by foursplaysroblox** [DmitryBorodiy/PowerWidgets#6]
please make PowerWidgets free please because i want to install it into my computer

**Comment by Scarlaid** [comment]
~~sounds like skill issue~~

**Comment by QuanTrieuPCYT** [comment]
- Requesting an open source program to be made 'free' in the issue section

- Also a dude bumping this one year old so-called problem

entirely comical

**Comment by foursplaysroblox** [comment]
Damn I forgot to close this issue

**Comment by QuanTrieuPCYT** [comment]
LOL

**Comment by foursplaysroblox** [comment]
I bought the app
